baseURL = "https://anas1412.github.io/notes/"
languageCode = "en-us"
title = "Notes from the Edge"
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']


# NO theme = "hugo-book" line here!

[module]
  [[module.imports]]
  path = "github.com/alex-shpak/hugo-book"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'



[menu]
# [[menu.before]]



[[menu.after]]
  name = "----------------------------------------------------"
  weight = 10   

[[menu.after]]
  name = "Website"
  url = "https://anas1412.github.io/"
  weight = 30
  
[[menu.after]]
  name = "Twitter"
  url = "https://x.com/villainesthetic"
  weight = 40

[[menu.after]]
  name = "Github"
  url = "https://github.com/anas1412"
  weight = 50






# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/anas1412/notes'
  BookSection = 'docs'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
  BookSearch = false