baseURL = "https://anas1412.github.io/notes/"
languageCode = "en-us"
title = "Notes from the Edge"
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']


# NO theme = "hugo-book" line here!

[module]
  [[module.imports]]
  path = "github.com/alex-shpak/hugo-book"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'



[markup.goldmark.renderer]
  unsafe = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/anas1412/notes'
  BookSection = 'docs'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
  BookSearch = false