baseURL = "https://anas1412.github.io/notes/"
languageCode = "en-us"
title = "Notes"

# NO theme = "hugo-book" line here!

[module]
  [[module.imports]]
  path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/anas1412/notes'
  BookSection = 'docs'
